---
title: "Packaging: Python"
---

## Learning Objectives {.unnumbered}

{{< include ../learning_objectives/191-packages-python.qmd >}}

## Essential Python package files

Using the project layout we recommend for this course,
here is a Python package structure with only the most essential files.

```bash
pkg
├── pyproject.toml
└── src
    └── pkg
        ├── __init__.py
        └── module.py
```

What do each of these do?

- `pyproject.toml` stores all the metadata and install instructions for the package.

- The presence of the `src` directory defines the code that will form the installable version of your package (meaning that users only get this code when they install the package, and that developers must install the package before running their tests).

- `__init__.py` tells Python that a directory is a package. They can be left empty, or they can also be used to add objects to the package’s namespace, provide documentation, and/or run other initialization code.

- `module.py` (this one can be named something else!) contains the functions you would like to share with your package users.
