project:
  type: book
  output-dir: ../docs

number-depth: 3

book:
  title: "Reproducible and Trustworthy Workflows for Data Science"
  author: "Tiffany A. Timbers, Joel Ostblom, Florencia D’Andrea, Rodolfo Lourenzutti, Daniel Chen"
  #date: "2024-10-28"
  search: true
  repo-url: https://github.com/UBC-DSCI/reproducible-and-trustworthy-workflows-for-data-science/
  #repo-actions: [edit]
  chapters:
    - index.qmd
    - part: parts/intro.qmd
      chapters:
      - lectures/010-intro-to-ds-workflows.qmd
      - lectures/020-intro-to-bash.qmd
    - part: parts/version-control.qmd
      chapters:
      - lectures/030-ssh-for-authentication.qmd
      - lectures/040-version-control-1.qmd
      - lectures/050-version-control-2.qmd
      - lectures/060-version-control-3.qmd
    - part: parts/projects-envs-containers.qmd
      chapters:
      - lectures/070-filenames-project-organization.qmd
      - lectures/080-virtual-environments.qmd
      - lectures/082-virtual_env-r-renv.qmd
      - lectures/085-virtual_env-python-conda.qmd
      - lectures/090-conda-lock.qmd
      - lectures/100-containerization-1.qmd
      - lectures/110-containerization-2.qmd
      - lectures/115-docker-compose.qmd
      - lectures/120-containerization-3.qmd
    - part: parts/data-validation.qmd
      chapters:
      - lectures/130-data-validation.qmd
      - lectures/131-data_validation-r-pointblank.qmd
      - lectures/135-data_validation-python-pandera.qmd
      - lectures/136-data_validation-python-deepchecks.qmd
    - part: parts/automation.qmd
      chapters:
      - lectures/150-scripts.qmd
      - lectures/160-reproducible-reports.qmd
      - lectures/170-pipelines-scripts.qmd
      - lectures/180-pipelines-make.qmd
    - part: parts/software-testing-for-data-science.qmd
      chapters:
      - lectures/140-intro-to-testing-code.qmd
      - lectures/142-R-testing-example.qmd
      - lectures/141-python-testing-example.qmd
      - lectures/147-testing-images.qmd
      - lectures/144-evaluating-test-suite-quality.qmd
    - part: parts/packaging.qmd
      chapters:
      - lectures/190-packaging-intro-python-r.qmd
      - lectures/191-packaging-python.qmd
      - lectures/192-packaging-r.qmd
      - lectures/193-packaging-conclusion.qmd
      - lectures/194-package-testing-python-pytest.qmd
      - lectures/196-coverage-r.qmd
      - lectures/197-coverage-python.qmd
    - part: parts/ci.qmd
      chapters:
      - lectures/200-continuous-integration.qmd
      - lectures/201-github_actions.qmd
      - lectures/201-actions-matrix.qmd
      - lectures/201-actions-testing.qmd
      - lectures/201-case_study_python.qmd
      - lectures/202-case_study_r.qmd
      - lectures/205-package_documentation_python.qmd
      - lectures/206-package_documentation_r.qmd
    - part: parts/cd.qmd
      chapters:
      - lectures/210-deploy-and-publish.qmd
      - lectures/211-gha_python.qmd
      - lectures/212-gha_r.qmd
      - lectures/213-package_review.qmd
    - part: parts/licenses-copyright-wrapup.qmd
      chapters:
      - lectures/220-licenses-and-copyright.qmd
      - lectures/230-reproducibility-wrap-up.qmd
    - part: parts/appendix.qmd
      chapters:
        - lectures/900-functions-in-python.qmd
        - lectures/910-functions-in-r.qmd
        - lectures/920-reproducible-reports.qmd

format:
  html:
    css: styles.css
    theme:
      - cosmo
  # pdf:
  #   documentclass: scrreprt

custom-callout:
  definition:
    icon: true
    icon-symbol: "📝"
    color: "pink"

  activity:
    icon: true
    icon-symbol: "🧩"
    color: "blue"

  exercise:
    icon: true
    icon-symbol: "🏋️"
    color: "green"

  relevance-project:
    title: Relevance to course project
    icon: true
    icon-symbol: "💻"
    color: "orange"

filters:
- custom-callout
