on:
    workflow_dispatch:
    pull_request:
      branches: main

name: Quarto PR Preview

jobs:
  build-deploy:
    runs-on: macos-latest # ubuntu-latest windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: book
